import assert from 'node:assert/strict';
import fs from 'node:fs';
import {skyboundCard,SKYBOUND_URL} from '../app/skybound-card.js';
const jsx={jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})};
for(const node of skyboundCard(jsx,false).props.children)assert.equal(node.props.href,SKYBOUND_URL);
for(const node of skyboundCard(jsx,true).props.children)assert.equal(node.props.href,undefined);
assert.match(SKYBOUND_URL,/\/skybound-soft\//);
const shared=fs.readFileSync(new URL('../app/chunk-A5QZM2VZ.js',import.meta.url),'utf8');
assert.ok(shared.includes('skyboundCard(e,!!a)'));
assert.ok(!shared.includes('obstaclePracticeCard'));
const html=fs.readFileSync(new URL('../skybound-soft/index.html',import.meta.url),'utf8');
const bundle=html.match(/src="\.\/(course-[^"?]+)/)[1];
const code=fs.readFileSync(new URL('../skybound-soft/'+bundle,import.meta.url),'utf8');
assert.ok(!code.includes('"/mini-oyunlar.html"'));
assert.ok(!code.includes('"/models/'));
assert.ok(code.includes('nt.rotation.y=kt*ft'));
assert.ok(code.includes('createSkyboundAvatar()'));
assert.ok(!code.includes('b2({base:"goril",body:null'));
assert.ok(html.includes('three/examples/jsm/'));
const avatar=fs.readFileSync(new URL('../app/skybound-avatar.js',import.meta.url),'utf8');
assert.ok(avatar.includes('chunk-U4P5F7P3.js'));
assert.ok(avatar.includes('const selected={...equipment}'));
assert.ok(avatar.includes('await avatar.animator.ready'));
assert.ok(code.includes('REMOVED_DECORATIVE_ISLAND'));
assert.ok(!code.includes('e.userData.courseFloor=[o,a]'));
assert.ok(code.includes('new ui("#fff7e8",0,9)'));
assert.ok(code.includes('gl_PointSize=min(48.0,'));
assert.ok(code.includes('if(mv.z>-0.35)'));
assert.ok(code.includes('Pt&&Math.abs(sn.position.x-Bt.position.x)<6'));
assert.ok(code.includes('sn.position.y<-9&&yi()'));
const spawn=code.slice(code.indexOf('function ke(Y){if(me(Y))'),code.indexOf('function Fe(Y,P={})',code.indexOf('function ke(Y){if(me(Y))')));
assert.ok(spawn.includes('Ke()'));
assert.ok(!spawn.includes('spawnBubble++'));
assert.ok(!spawn.includes('ae.emit'));
assert.ok(!spawn.includes('se(Y,8384767'));
assert.ok(SKYBOUND_URL.includes('skybound-44'));
console.log('PASS Skybound card, solo route, disabled room state, subpath assets and pause clock');
